
project_id = "ypedypnxcsikqvzjqcvy"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["extensions"]
max_rows = 1000

[functions]
[functions.send-order-confirmation]
verify_jwt = false
